[project]
authors = [
  {name = "Hassan Umari", email = "oh91@windowslive.com"},
]
dependencies = [
  "numpy>=1.20.0",
  "pytest-cov>=4.0.0",
  "matplotlib>=3.5.0",
]
description = "Add your description here"
name = "trajectory_retiming"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

[project.scripts]
trajectory_retiming = "robotics_challenge_take_home:main"

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.12.5,<0.13.0"]

[dependency-groups]
dev = [
  "ipython==8.0.0",
  "pytest>=7.0.0",
]

[tool.pytest.ini_options]
testpaths = ["test"]
